sudo: false
language: node_js
node_js:
  - 8
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ./app/.npmrc
env:
  - TEST_DIR=app
  - TEST_DIR=client
script: cd $TEST_DIR && npm install && npm test

